let shopItemsData = [
  {
    id: 1,
    name: "Awesome Product",
    price: 28,
    priceAfterDiscount: 25,
    imageName: "cat1",
    isNew: "TRUE",
    rating: "3",
    img: "./images/product1.png",
  },
  {
    id: 2,
    name: "Cool Product",
    price: 63,
    priceAfterDiscount: 40,
    imageName: "cat2",
    isNew: "FALSE",
    rating: "4",
    img: "./images/product2.png",
  },
  {
    id: 3,
    name: "Amazing Product",
    price: 26,
    priceAfterDiscount: 19,
    imageName: "cat3",
    isNew: "FALSE",
    rating: "2",
    img: "./images/product3.png",
  },
  {
    id: 4,
    name: "Huge Product",
    price: 58,
    priceAfterDiscount: 50,
    imageName: "cat4",
    isNew: "TRUE",
    rating: "4",
    img: "./images/product4.png",
  },
  {
    id: 5,
    name: "Tiny Product",
    price: 58,
    priceAfterDiscount: 48,
    imageName: "cat5",
    isNew: "FALSE",
    rating: "5",
    img: "./images/product5.png",
  },
  {
    id: 6,
    name: "Expensive Product",
    price: 82,
    priceAfterDiscount: 77,
    imageName: "cat6",
    isNew: "TRUE",
    rating: "5",
    img: "./images/product6.png",
  },
];
